apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: tier-2-ingress
  annotations:
     kubernetes.io/ingress.class: "tier-2-cpx"
     kubernetes.io/insecure-port: "80"
spec:
  rules:
  - host: sockshop.com
    http:
      paths:
      - path: /
        backend:
          serviceName: front-end
          servicePort: 80
